spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lsgggg123?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
    username: x
    password: x
    driverClassName: com.mysql.jdbc.Driver
    validationQuery: SELECT 1
    initialSize: 10
    maxActive: 30
    minIdle: 10

server:
  contextPath: /mybatis
  port: 8080