spring:
  application:
    name: zuul-gateway

zuul:
  routes:
    feignclient-client:
      path: /fc/**
      url: http://localhost:8080

ribbon:
  eureka:
    enabled: false

server:
  port: 8088

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/