spring:
  application:
    name: zuul-gateway

server:
  port: 8088

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

#zuul:
  #routes:
    #feignclient-client:
      #path: /fc/**
      #url: http://localhost:8080

#ribbon:
  #eureka:
    #enabled: false

zuul:
  routes:
    cloud-service:
      path: /api/**
      serviceId: cloud-service