server:
  context-path: feignclient-clien
  port: 8080

spring:
  application:
    name: feignclient-client

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

apply:
  message: local message
user:
  username: lsgggg123